### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by ZClee128** [miliPolo/SwiftUI_Jike#1]
clone下来，项目运行报错，一堆方法说找不到

**Comment by gakaki** [comment]
https://github.com/gakaki/SwiftUI_JIKE      我fork了一个 可以直接这里 已@作者

**Comment by TranCoffee** [comment]
> https://github.com/gakaki/SwiftUI_JIKE 我fork了一个 可以直接这里 已@作者

赞赞赞！
